"""
Skynet — Astronomy Q&A Chatbot Backend
=======================================
FastAPI server that answers astronomy questions using an extensive
built-in knowledge base with fuzzy keyword matching.

Run:
    pip install fastapi uvicorn
    python Skynet.py
    # or: uvicorn Skynet:app --reload --port 8000

Endpoint:
    POST /chat  { "message": "..." }  →  { "reply": "..." }
"""

import sys
import re
import random
from datetime import datetime
from typing import Optional

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel


# ============================================================
# APP
# ============================================================

app = FastAPI(title="Skynet", version="2.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ============================================================
# LOGGING
# ============================================================

def log(tag: str, msg: str) -> None:
    t = datetime.now().strftime("%H:%M:%S")
    print(f"[{t}] [{tag}] {msg}", file=sys.stderr)


# ============================================================
# KNOWLEDGE BASE
# ============================================================

KNOWLEDGE: dict[str, list[str]] = {

    # ── Solar System ─────────────────────────────────────────

    "sun": [
        "The Sun is a G-type main-sequence star (G2V) at the center of our solar system. "
        "It accounts for ~99.86% of the total mass of the solar system.",
        "Surface temperature: ~5,778 K. Core temperature: ~15.7 million K. "
        "It fuses ~620 million metric tons of hydrogen every second.",
        "The Sun is about 4.6 billion years old and is roughly halfway through "
        "its main-sequence life. In ~5 billion years it will expand into a red giant.",
    ],

    "mercury": [
        "Mercury is the smallest planet and closest to the Sun. "
        "It has no atmosphere to retain heat, so temperatures swing from −180°C to 430°C.",
        "A day on Mercury (sunrise to sunrise) lasts 176 Earth days, "
        "but its year is only 88 Earth days — so a day is longer than its year.",
        "Mercury has a large iron core — about 85% of its radius — "
        "and a weak magnetic field, roughly 1% the strength of Earth's.",
    ],

    "venus": [
        "Venus is often called Earth's twin because of its similar size, but it has a "
        "crushing CO₂ atmosphere with surface pressures ~92× Earth's and temperatures of ~465°C.",
        "Venus rotates retrograde (clockwise when viewed from above the north pole) "
        "and its rotation is slower than its orbit — a Venusian day is ~243 Earth days.",
        "The surface of Venus is hidden by thick sulfuric acid clouds. "
        "The Soviet Venera missions are the only spacecraft to have returned surface photos.",
    ],

    "earth": [
        "Earth is the only known planet to support life. Its atmosphere is 78% N₂, 21% O₂. "
        "Liquid water covers ~71% of the surface.",
        "Earth's magnetic field, generated by its molten iron outer core, "
        "shields the surface from solar wind and cosmic radiation.",
        "The Moon stabilizes Earth's axial tilt at ~23.5°, which is key to "
        "the planet's seasonal climate patterns.",
    ],

    "moon": [
        "The Moon is Earth's only natural satellite, with a diameter of 3,474 km (~¼ Earth's). "
        "It is tidally locked, so the same face always points toward Earth.",
        "The leading theory for the Moon's formation is the Giant Impact Hypothesis — "
        "a Mars-sized body (Theia) collided with early Earth ~4.5 billion years ago.",
        "The Moon has no atmosphere and its surface gravity is ~1/6 of Earth's. "
        "12 humans have walked on its surface during the Apollo program (1969–1972).",
    ],

    "mars": [
        "Mars is the fourth planet from the Sun, known as the Red Planet due to iron oxide on its surface. "
        "Its thin CO₂ atmosphere means surface pressure is only ~0.6% of Earth's.",
        "Mars hosts the tallest volcano in the solar system — Olympus Mons at 21.9 km — "
        "and the vast Valles Marineris canyon system stretching over 4,000 km.",
        "Evidence of ancient river channels and subsurface water ice strongly suggests "
        "Mars once had liquid water. Multiple rovers (Curiosity, Perseverance) are actively exploring it.",
    ],

    "jupiter": [
        "Jupiter is the largest planet in our solar system — over 1,300 Earths could fit inside. "
        "It is a gas giant with no solid surface, mostly hydrogen and helium.",
        "The Great Red Spot is a persistent anticyclonic storm larger than Earth, "
        "observed since at least 1831 and possibly since 1665.",
        "Jupiter has 95 known moons. The four Galilean moons — Io, Europa, Ganymede, and Callisto — "
        "were discovered by Galileo in 1610. Europa likely harbors a subsurface ocean.",
    ],

    "saturn": [
        "Saturn is famous for its spectacular ring system, made mostly of ice particles and rocky debris "
        "ranging from micrometers to meters in size.",
        "Saturn is the least dense planet — its bulk density of 0.687 g/cm³ is less than water. "
        "Theoretically, it would float if you had a big enough bathtub.",
        "Titan, Saturn's largest moon, has a thick nitrogen atmosphere and liquid methane/ethane lakes — "
        "it is the only moon with a dense atmosphere and surface liquids.",
    ],

    "uranus": [
        "Uranus is an ice giant tilted ~98° on its axis — it essentially orbits the Sun on its side. "
        "This extreme tilt is likely the result of a giant impact early in its history.",
        "Uranus has 27 known moons, all named after characters from Shakespeare and Alexander Pope. "
        "Its atmosphere contains methane which absorbs red light, giving it a blue-green color.",
    ],

    "neptune": [
        "Neptune is the most distant planet from the Sun. It has the strongest sustained winds "
        "in the solar system, exceeding 2,100 km/h.",
        "Triton, Neptune's largest moon, orbits retrograde and is likely a captured Kuiper Belt object. "
        "It has geysers of nitrogen gas and may harbor a subsurface ocean.",
    ],

    "pluto": [
        "Pluto was reclassified as a dwarf planet in 2006 by the IAU. "
        "NASA's New Horizons flew past it in 2015, revealing a complex surface with nitrogen ice plains.",
        "Pluto has five known moons. Charon, the largest, is so big relative to Pluto "
        "that the barycenter of their orbit lies outside Pluto itself — sometimes called a double dwarf planet.",
    ],

    # ── Stars & Stellar Evolution ────────────────────────────

    "star": [
        "Stars form in molecular clouds (nebulae) when gravity overcomes gas pressure. "
        "They spend most of their lives on the main sequence fusing hydrogen into helium.",
        "A star's fate depends on its mass: low-mass stars become white dwarfs, "
        "high-mass stars explode as supernovae leaving neutron stars or black holes.",
        "The Hertzsprung-Russell diagram plots stars by luminosity vs temperature — "
        "most fall on the main sequence, with giants and white dwarfs in separate branches.",
    ],

    "neutron star": [
        "Neutron stars are the collapsed cores of massive stars after a supernova. "
        "They pack ~1.4–2 solar masses into a sphere only ~20 km across.",
        "A teaspoon of neutron star material would weigh about 6 billion tons on Earth. "
        "The fastest known pulsar spins at 716 rotations per second.",
    ],

    "black hole": [
        "A black hole forms when a massive star collapses beyond its Schwarzschild radius, "
        "creating a region where gravity is so strong that nothing — not even light — can escape.",
        "The Event Horizon Telescope captured the first direct image of a black hole's shadow "
        "in M87 in 2019, confirming predictions of General Relativity.",
        "Supermassive black holes (millions to billions of solar masses) reside at the centers "
        "of most galaxies, including Sagittarius A* at the center of the Milky Way.",
    ],

    "supernova": [
        "A supernova is the explosive death of a massive star, briefly outshining its entire galaxy. "
        "Type II supernovae are core-collapse events; Type Ia result from white dwarf detonation.",
        "Supernovae seed the interstellar medium with heavy elements (carbon, oxygen, iron, gold). "
        "All elements heavier than iron in your body were forged in a supernova or neutron star merger.",
    ],

    "nebula": [
        "A nebula is a giant cloud of gas and dust in space. Some are stellar nurseries "
        "(like the Orion Nebula), while others are remnants of dead stars (like the Crab Nebula).",
        "Planetary nebulae are shells of gas expelled by dying low-mass stars — they have nothing "
        "to do with planets; the name comes from their round appearance in early telescopes.",
    ],

    # ── Galaxies & Cosmology ──────────────────────────────────

    "galaxy": [
        "A galaxy is a gravitationally bound system of stars, gas, dust, and dark matter. "
        "The Milky Way contains 100–400 billion stars and is ~100,000 light-years across.",
        "Galaxies are classified into spirals, ellipticals, and irregulars (Hubble sequence). "
        "The Milky Way is a barred spiral galaxy (SBbc).",
        "The Milky Way and Andromeda (M31) are on a collision course and will merge "
        "in approximately 4.5 billion years to form 'Milkdromeda'.",
    ],

    "milky way": [
        "The Milky Way is our home galaxy — a barred spiral ~100,000 light-years in diameter "
        "with a supermassive black hole (Sagittarius A*, ~4 million solar masses) at its center.",
        "Our solar system orbits the galactic center at ~828,000 km/h, "
        "completing one galactic year every ~225–250 million years.",
    ],

    "dark matter": [
        "Dark matter makes up ~27% of the universe's mass-energy content. "
        "It doesn't emit or absorb light, but its gravitational effects are observable — "
        "e.g., galaxy rotation curves, gravitational lensing, and the CMB.",
        "Leading candidates include WIMPs (Weakly Interacting Massive Particles) and axions. "
        "Despite decades of experiments, dark matter has never been directly detected.",
    ],

    "dark energy": [
        "Dark energy accounts for ~68% of the universe and is driving the accelerating expansion "
        "of the cosmos. It was discovered in 1998 via distant Type Ia supernovae observations.",
        "The nature of dark energy remains one of the biggest mysteries in physics. "
        "It may be a cosmological constant (Λ) or a dynamic field (quintessence).",
    ],

    "big bang": [
        "The Big Bang theory describes the universe's origin ~13.8 billion years ago from an "
        "extremely hot, dense state. It is supported by the CMB, Hubble expansion, and nucleosynthesis.",
        "In the first three minutes after the Big Bang, protons and neutrons formed the lightest "
        "elements (hydrogen, helium, traces of lithium). Stars later forged heavier elements.",
    ],

    "cosmic microwave background": [
        "The CMB is relic radiation from ~380,000 years after the Big Bang, when the universe "
        "cooled enough for atoms to form, making it transparent to photons for the first time.",
        "Discovered accidentally by Penzias and Wilson in 1965, the CMB has a temperature of "
        "~2.725 K and tiny fluctuations (~1 part in 100,000) that seeded cosmic structure.",
    ],

    # ── Space Exploration ─────────────────────────────────────

    "apollo": [
        "The Apollo program (1961–1972) landed 12 humans on the Moon across six missions. "
        "Apollo 11 (July 20, 1969) saw Neil Armstrong become the first human on the lunar surface.",
        "Apollo 13 (1970) suffered an oxygen tank explosion but the crew returned safely — "
        "a landmark of mission control problem-solving.",
    ],

    "iss": [
        "The International Space Station orbits Earth at ~408 km altitude, "
        "traveling at ~28,000 km/h and completing an orbit every ~90 minutes.",
        "The ISS is a collaboration between NASA, Roscosmos, ESA, JAXA, and CSA. "
        "It has been continuously occupied since November 2000.",
    ],

    "james webb": [
        "The James Webb Space Telescope (JWST), launched December 2021, is the most powerful "
        "space telescope ever built. Its 6.5 m primary mirror observes in infrared.",
        "JWST orbits the Sun–Earth L2 point (~1.5 million km from Earth). "
        "Its sunshield is the size of a tennis court and keeps instruments at −233°C.",
    ],

    "hubble": [
        "The Hubble Space Telescope has been in low Earth orbit since 1990. "
        "It has made over 1.5 million observations and fundamentally changed astronomy.",
        "Hubble's observations of distant Type Ia supernovae provided the first evidence "
        "for the accelerating expansion of the universe.",
    ],

    "voyager": [
        "Voyager 1 and 2 were launched in 1977. Voyager 1 entered interstellar space in 2012, "
        "becoming the most distant human-made object at over 24 billion km from Earth.",
        "Both Voyagers carry a Golden Record with sounds and images of Earth, "
        "intended as a message to any extraterrestrial civilization that might find them.",
    ],

    "spacex": [
        "SpaceX, founded by Elon Musk in 2002, developed the first privately-funded liquid-fuel "
        "rocket to reach orbit (Falcon 1) and the first reusable orbital rocket (Falcon 9).",
        "Starship, SpaceX's next-generation launch vehicle, is the largest and most powerful "
        "rocket ever built, designed for missions to the Moon, Mars, and beyond.",
    ],

    # ── Constellations ───────────────────────────────────────

    "constellation": [
        "There are 88 officially recognized constellations, defined by the IAU in 1922. "
        "They cover the entire celestial sphere and are used for navigation and star identification.",
        "The zodiac constellations lie along the ecliptic — the apparent path of the Sun across "
        "the sky. The Sun actually passes through 13 constellations (including Ophiuchus).",
    ],

    "orion": [
        "Orion is one of the most recognizable constellations, visible from both hemispheres. "
        "Its three belt stars (Alnitak, Alnilam, Mintaka) are a famous asterism.",
        "Betelgeuse, a red supergiant in Orion's shoulder, is expected to go supernova "
        "within the next ~100,000 years. It would be visible in daylight.",
    ],

    # ── Physics Concepts ──────────────────────────────────────

    "light year": [
        "A light-year is the distance light travels in one year: ~9.461 trillion km (5.879 trillion miles). "
        "It is a unit of distance, not time.",
        "The nearest star system to the Sun is Alpha Centauri, at ~4.37 light-years away.",
    ],

    "gravity": [
        "Gravity is described by Einstein's General Relativity as the curvature of spacetime "
        "caused by mass and energy. Newton's law of universal gravitation approximates it for weak fields.",
        "Gravitational waves — ripples in spacetime — were first directly detected by LIGO in 2015 "
        "from the merger of two black holes ~1.3 billion light-years away.",
    ],

    "exoplanet": [
        "An exoplanet is a planet orbiting a star other than the Sun. Over 5,500 have been confirmed "
        "as of 2024, primarily by the Kepler and TESS missions.",
        "The most common detection methods are the transit method (dips in stellar brightness) "
        "and radial velocity (Doppler wobble of the host star).",
        "Some exoplanets orbit in the habitable zone where liquid water could exist. "
        "Proxima Centauri b, just 4.24 light-years away, is one such candidate.",
    ],

    "asteroid": [
        "Asteroids are rocky remnants from the early solar system. Most reside in the asteroid belt "
        "between Mars and Jupiter, but near-Earth asteroids pose potential impact risks.",
        "NASA's DART mission successfully altered the orbit of asteroid Dimorphos in 2022, "
        "demonstrating kinetic impactor technology for planetary defense.",
    ],

    "comet": [
        "Comets are icy bodies that develop tails of gas and dust when they approach the Sun. "
        "Short-period comets come from the Kuiper Belt; long-period comets from the Oort Cloud.",
        "Halley's Comet visits the inner solar system roughly every 75–79 years. "
        "Its next perihelion passage is expected in 2061.",
    ],
}

# ── Greeting / fallback responses ────────────────────────────

GREETINGS = [
    "Hello, operator. Skynet is online. Ask me anything about the cosmos.",
    "Greetings. Skynet astronomy module active. What would you like to know?",
    "Welcome back. Query the cosmos — I'm ready.",
]

FALLBACKS = [
    "I don't have specific data on that yet. Try asking about a planet, star, black hole, "
    "nebula, space mission, or cosmological concept.",
    "That's outside my current knowledge base. I can answer questions about "
    "the solar system, stellar evolution, galaxies, space missions, and more.",
    "Interesting question — I'll need an update to answer it. "
    "Meanwhile, try topics like 'Jupiter', 'black hole', 'JWST', or 'dark matter'.",
]


# ============================================================
# MATCHING ENGINE
# ============================================================

def normalize(text: str) -> str:
    return re.sub(r"[^a-z0-9\s]", "", text.lower()).strip()


def find_best_match(message: str) -> Optional[str]:
    """Fuzzy match user message against knowledge base keys."""
    msg = normalize(message)

    # Direct key match
    for key in KNOWLEDGE:
        if key in msg:
            return key

    # Word-level overlap scoring
    words = set(msg.split())
    best_key = None
    best_score = 0

    for key in KNOWLEDGE:
        key_words = set(key.split())
        overlap = len(words & key_words)
        if overlap > best_score:
            best_score = overlap
            best_key = key

    return best_key if best_score > 0 else None


def generate_reply(message: str) -> str:
    """Generate a reply from the knowledge base."""
    msg = normalize(message)

    # Handle greetings
    greetings = {"hello", "hi", "hey", "greetings", "sup", "yo"}
    if msg in greetings or (len(msg.split()) <= 3 and any(g in msg for g in greetings)):
        return random.choice(GREETINGS)

    key = find_best_match(message)

    if key:
        entries = KNOWLEDGE[key]
        # Return 1–2 entries for a balanced response
        count = min(2, len(entries))
        selected = random.sample(entries, count)
        return "\n\n".join(selected)

    return random.choice(FALLBACKS)


# ============================================================
# API
# ============================================================

class ChatRequest(BaseModel):
    message: str


class ChatResponse(BaseModel):
    reply: str


@app.post("/chat", response_model=ChatResponse)
async def chat(req: ChatRequest):
    log("CHAT", f"IN: {req.message[:100]}")
    reply = generate_reply(req.message)
    log("CHAT", f"OUT: {reply[:100]}")
    return ChatResponse(reply=reply)


@app.get("/health")
async def health():
    return {"status": "ok", "service": "skynet", "version": "2.0.0"}


# ============================================================
# ENTRY
# ============================================================

if __name__ == "__main__":
    import uvicorn

    log("SYSTEM", "Skynet v2.0 — Astronomy Chatbot starting on :8000")
    uvicorn.run(app, host="0.0.0.0", port=8000)